### ISSUE TITLE
Full-Screen Application - Mouse wiggle opens shelf and exits App

### ISSUE THREAD

**Issue by TheBrokenG0d** [williamckha/dropshelf-issues#6]
### ℹ️ System information

```Markdown
- Dropshelf version: Latest Windows Store build
- Windows version and OS build: Win11 build 22631
```

### 📝 Description

If you are in a full-screen application e.g. a video game and you do the mouse click and wiggle it will exit from the application and open a shelf even if no files were selected.

### Steps to reproduce

1. Open Full-Screen Application
2. Hold click the mouse and wiggle.
3. exists from Full-Screen Application

**Comment by williamckha** [comment]
Thanks for using Dropshelf. The latest update [v1.0.4.0](https://github.com/williamckha/dropshelf-issues/releases/tag/v1.0.4.0) is live in the Microsoft Store and fixes this issue.
